//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRMDataManager.Library.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GRMContext : DbContext
    {
        public GRMContext()
            : base("name=GRMContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // configures one-to-many relationship
            modelBuilder.Entity<Sale>()
                .HasRequired<User>(s => s.User)
                .WithMany(g => g.Sales)
            .HasForeignKey<string>(s => s.CashierId);

            modelBuilder.Entity<SaleDetail>()
                .HasRequired<Sale>(s => s.Sale)
                .WithMany(g => g.SaleDetails)
            .HasForeignKey<int>(s => s.SaleId);

            modelBuilder.Entity<SaleDetail>()
                .HasRequired<Product>(s => s.Product)
                .WithMany(g => g.SaleDetails)
                .HasForeignKey<int>(s => s.ProductId);

            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SaleDetail> SaleDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
