//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRMDataManager.Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Descrption { get; set; }
        public decimal RetailPrice { get; set; }
        public int QuantityInStock { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool IsTaxable { get; set; }
    }
}
